#!/bin/bash
sort | uniq -u
[master 797ea40] task 13
 2 files changed, 2 insertions(+)
 create mode 100755 0x02-shell_redirections/13-unique
 mode change 100755 => 100644 0x02-shell_redirections/README.md
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   13-unique

no changes added to commit (use "git add" and/or "git commit -a")
